{% set name = "wwt_kernel_data_relay" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/wwt_kernel_data_relay-{{ version }}.tar.gz
  sha256: 05ff7579659fb3b08473101da548c23f7c7cb339163e2c17eff0dcbb7003cc51

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - jupyter-packaging
    - pip
    - python >=3.7
  run:
    - jupyter_client >=7
    - notebook >=6
    - python >=3.7
    - tornado >=6
    - traitlets >=5

test:
  imports:
    - wwt_kernel_data_relay
  commands:
    - pip check
    - jupyter serverextension list 2>&1 |grep 'wwt_kernel_data_relay.*OK'
  requires:
    - jupyter_core
    - notebook
    - pip

about:
  home: https://github.com/WorldWideTelescope/wwt_kernel_data_relay/
  summary: Jupyter server extension to allow kernels to make data web-accessible
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - pkgw
