{% set name = "wwt_kernel_data_relay" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/wwt_kernel_data_relay-{{ version }}.tar.gz
  sha256: a48f880f6d5c49bbd699b1e48365c8440ca23c49cde5800e9c232870c7f3515f

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - jupyter-packaging
    - pip
    - python {{ python_min }}
  run:
    - jupyter_client >=7
    - jupyter_server >=2
    - python >={{ python_min }}
    - tornado >=6
    - traitlets >=5

test:
  imports:
    - wwt_kernel_data_relay
  commands:
    - pip check
    - jupyter nbclassic-serverextension list 2>&1 |grep 'wwt_kernel_data_relay.*OK'
  requires:
    - jupyter_core
    - jupyter_server
    - nbclassic
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/WorldWideTelescope/wwt_kernel_data_relay/
  summary: Jupyter server extension to allow kernels to make data web-accessible
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - pkgw
